name: Log message

on:
  workflow_dispatch:
    inputs:
      text:
        description: "Text to log"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Console
        run: echo "${{ inputs.text }}"
